# Generated by Django 5.1.1 on 2024-10-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="form",
        ),
        migrations.RemoveField(
            model_name="product",
            name="topic",
        ),
        migrations.AddField(
            model_name="product",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.form",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.topic",
            ),
        ),
    ]
