# Generated by Django 5.1.1 on 2024-10-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_product_form_remove_product_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.form",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.topic",
            ),
        ),
    ]
