# Generated by Django 5.1.1 on 2024-10-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="product",
            name="material",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
